### ISSUE TITLE
Ship 1.12.1 and 2.0.0 to conda-forge?

### ISSUE THREAD

**Issue by rjurney** [conda-forge/flask-appbuilder-feedstock#19]
Would it be possible to ship 0.12.1 and 0.14.0 to conda-forge?

**Comment by xylar** [comment]
@rjurney, I don't see any such versions in the history: https://pypi.org/project/Flask-AppBuilder/#history

Are you sure you have the right feedstock or the right version numbers?

**Comment by rjurney** [comment]
It looks like he didn’t publish 1.4 to Pypi, that might be 2.0 but I’m not sure. He indicated he’d be doing that yesterday. 0.12.1 is there.

**Comment by xylar** [comment]
I think you mean `1.12.1` instead of `0.12.1` and `1.14.0` intead of `0.14.0`.

I just built 6 versions today -- 1.12.0, 1.12.1, 1.12.2, 1.12.3, 1.12.4, 1.12.5.  Two of the dependencies for 1.13.0 and 2.0.0 are not on conda-forge (see #23).  Feel free to help with those dependencies.  I'll try to make a recipe when I get a chance but I'm just a volunteer like everyone else here and this isn't a package I need for my own research.

**Comment by rjurney** [comment]
Whoops, sorry! I meant 1.12.1 and 1.14.0. Thanks, yeah I figured I would do the work. I just wanted to file a ticket for it first.

**Comment by xylar** [comment]
@rjurney, I've got PRs in for the missing dependencies for 1.13.0 and 2.0.0:
https://github.com/conda-forge/staged-recipes/pull/8174
https://github.com/conda-forge/staged-recipes/pull/8175
The missing license from `prison` is likely to be a problem.  If the developer doesn't respond quickly, there's not really anything i can do.

**Comment by xylar** [comment]
Update: `marshmallow-enum` is in.  We're just waiting on `prison`, and I've added the needed license there so that should be okay to go.  Maybe another day or 2.

**Comment by xylar** [comment]
@rjurney these are both in.  You may have to wait a bit until they show up when you `conda create` or `conda install`.

**Comment by rjurney** [comment]
@xylar Thanks!
